-- CreateTable
CREATE TABLE "health_biometrics" (
    "id" TEXT NOT NULL,
    "customerProfileId" TEXT NOT NULL,
    "heightCm" DOUBLE PRECISION NOT NULL,
    "weightKg" DOUBLE PRECISION NOT NULL,
    "targetWeightKg" DOUBLE PRECISION,
    "muscleMassKg" DOUBLE PRECISION,
    "occupation" TEXT,
    "workSchedule" TEXT,
    "sleepDuration" DOUBLE PRECISION,
    "wakeUpTime" TEXT,
    "bedTime" TEXT,
    "circumferences" JSONB,
    "limbCircumferences" JSONB,
    "goal" TEXT NOT NULL,
    "primaryGoals" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "activityLevel" TEXT NOT NULL,
    "hasExercise" BOOLEAN NOT NULL DEFAULT false,
    "workoutTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "workoutFrequency" TEXT,
    "workoutDuration" INTEGER,
    "dailyStepCount" INTEGER,
    "cardioSessions" INTEGER,
    "strengthSessions" INTEGER,
    "medicalConditions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "currentMedications" TEXT,
    "supplements" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "bloodTestResults" JSONB,
    "foodPreference" TEXT,
    "allergies" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "foodDislikes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "customQuery" TEXT,
    "mealsPerDay" INTEGER NOT NULL DEFAULT 3,
    "mealTimings" JSONB,
    "waterIntakeL" DOUBLE PRECISION,
    "digestiveHealth" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "smoking" TEXT,
    "alcohol" TEXT,
    "tobacco" TEXT,
    "stressLevel" INTEGER,
    "sleepQuality" TEXT,
    "isPregnant" BOOLEAN,
    "isBreastfeeding" BOOLEAN,
    "menstrualCycle" TEXT,
    "isMenopause" BOOLEAN,
    "planDurationDays" INTEGER,
    "planFrequency" INTEGER,
    "preferredSlot" TEXT,
    "addonSlots" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "bmi" DOUBLE PRECISION NOT NULL,
    "bmiCategory" TEXT NOT NULL,
    "bmr" INTEGER NOT NULL,
    "tdee" INTEGER NOT NULL,
    "maintenanceCalories" INTEGER NOT NULL,
    "targetCalories" INTEGER NOT NULL,
    "macroTargets" JSONB NOT NULL,
    "waterRequirementL" DOUBLE PRECISION,
    "idealBodyWeightKg" DOUBLE PRECISION,
    "leanBodyMassKg" DOUBLE PRECISION,
    "calorieDeficitSurplus" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "health_biometrics_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "health_biometrics_customerProfileId_key" ON "health_biometrics"("customerProfileId");

-- AddForeignKey
ALTER TABLE "health_biometrics" ADD CONSTRAINT "health_biometrics_customerProfileId_fkey" FOREIGN KEY ("customerProfileId") REFERENCES "customer_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
